# Generated by Django 5.0.1 on 2024-02-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedIQ_Advisor_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mental_health_survey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
